In [33]:
import numpy as np
import seaborn as sns

from collections import OrderedDict
from ont_fast5_api.fast5_interface import get_fast5_file

%matplotlib inline

In [34]:
# fast5_path = ""
# reads = OrderedDict()
# with get_fast5_file(fast5_path, mode="r") as f5:
#     for read in f5.get_reads():
#         raw_data = read.get_raw_data()
#         reads[read.read_id] = raw_data

In [35]:
# read_id = list(reads.keys())[1]
# reads[read_id]

In [36]:
# sns.lineplot(reads[read_id][:500])

### subsample dataset
get a small (1000 signals) to check the correctness of the code and training

In [37]:
import h5py
import numpy as np
from pathlib import Path

In [38]:
PATH_DATA="/extdata/RODAN/"
recfile = Path(PATH_DATA).joinpath("train/rna-train.hdf5")
h5 = h5py.File(recfile)

In [39]:
for at in h5.attrs:
    print(at)

In [40]:
h5["events"][:1000]

array([[ 0.1527149 ,  0.3054298 ,  0.29906666, ..., -0.9226525 ,
        -0.90992624, -1.0117362 ],
       [-1.0499148 , -0.9035631 , -1.0180993 , ..., -0.85902125,
        -0.8081163 , -0.8781106 ],
       [-1.0626411 , -1.0753673 , -0.7635744 , ...,  0.636312  ,
         0.9162893 ,  0.79539007],
       ...,
       [-0.22753905, -0.20315987, -0.2925502 , ...,  0.9507882 ,
         1.5683942 ,  1.6334053 ],
       [ 0.83701867,  2.1697474 ,  0.885777  , ..., -0.21941265,
         0.12189592,  0.16252789],
       [-0.07313755,  0.04063197, -0.09751674, ...,  0.99142015,
         1.0483049 ,  0.9345354 ]], dtype=float32)

In [41]:
h5["labels"][:1000]

array([[4, 3, 4, ..., 0, 0, 0],
       [4, 2, 4, ..., 0, 0, 0],
       [4, 3, 4, ..., 0, 0, 0],
       ...,
       [2, 1, 1, ..., 0, 0, 0],
       [2, 4, 1, ..., 0, 0, 0],
       [1, 1, 2, ..., 0, 0, 0]])

In [42]:
h5["events"]

<HDF5 dataset "events": shape (1000002, 4096), type "<f4">

In [43]:
N_SAMPLES = 1000
f = h5py.File("../data/subsample_train.hdf5", "w")
dset = f.create_dataset("subsample_train", (N_SAMPLES,))
f["events"] = h5["events"][:N_SAMPLES]
f["labels"] = h5["labels"][:N_SAMPLES]
f.close()

(1000,)

In [50]:
N_SAMPLES_VAL = 200
f = h5py.File("../data/subsample_val.hdf5", "w")
dset = f.create_dataset("subsample_val", (N_SAMPLES,))
f["events"] = h5["events"][N_SAMPLES:N_SAMPLES+N_SAMPLES_VAL]
f["labels"] = h5["labels"][N_SAMPLES:N_SAMPLES+N_SAMPLES_VAL]
f.close()

In [51]:
g = h5py.File("../data/subsample_val.hdf5", "r")
g["events"].shape, g["labels"].shape

((200, 4096), (200, 271))

In [52]:
g["events"][0]

array([0.82889223, 0.84514505, 0.86952424, ..., 1.2839704 , 1.4058663 ,
       1.113316  ], dtype=float32)

In [53]:
g.close()